objects/Procurement_Savings_Project__c.object
<CustomObject>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Procurement Savings Projects</relationshipLabel>
        <relationshipName>Procurement_Savings_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Actuals__c</fullName>
        <label>Total Actuals</label>
        <summarizedField>Procurement_Savings_Project_Forecast__c.Total_Actuals__c</summarizedField>
        <summaryForeignKey>Procurement_Savings_Project_Forecast__c.Procurement_Savings_Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Forecast__c</fullName>
        <label>Total Forecast</label>
        <summarizedField>Procurement_Savings_Project_Forecast__c.Total_Forecast__c</summarizedField>
        <summaryForeignKey>Procurement_Savings_Project_Forecast__c.Procurement_Savings_Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Procurement Savings Project</label>
    <nameField>
        <label>Procurement Savings Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procurement Savings Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Supplier__c.object
<CustomObject>
    <fields>
        <fullName>Total_Forecast__c</fullName>
        <label>Total Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProjectTriggerHandler.cls
public class ProjectTriggerHandler {
    
    public static void checkSupplierOnProcurementSavingsProject(Map<Id, Procurement_Savings_Project__c> newMap, Map<Id, Procurement_Savings_Project__c> oldMap){
        
        // Insert and Update.
        List<Procurement_Savings_Project__c> procurementSavingsProjects = new List<Procurement_Savings_Project__c>();
        Set<Id> supplierIds = new Set<Id>();
        
        if(Trigger.isInsert){
            procurementSavingsProjects = newMap.values();
        }if(Trigger.isDelete){
            procurementSavingsProjects = oldMap.values();
        }if(Trigger.isUpdate){
            procurementSavingsProjects = newMap.values();
        }
        
        for(Procurement_Savings_Project__c procurementSavingsProject : procurementSavingsProjects){
            if(procurementSavingsProject.Supplier__c != null){
                supplierIds.add(procurementSavingsProject.Supplier__c);
            }
            
            // Udpate
            if(Trigger.isUpdate){
                if((oldMap.get(procurementSavingsProject.Id).Supplier__c != procurementSavingsProject.Supplier__c)){                    
                    supplierIds.add(procurementSavingsProject.Supplier__c);
                    supplierIds.add(oldMap.get(procurementSavingsProject.Id).Supplier__c);
                }
                
                if(((oldMap.get(procurementSavingsProject.Id).Total_Actuals__c != procurementSavingsProject.Total_Actuals__c) || 
                   (oldMap.get(procurementSavingsProject.Id).Total_Forecast__c != procurementSavingsProject.Total_Forecast__c) ) &&
                   procurementSavingsProject.Supplier__c != null
                  ){

                      supplierIds.add(procurementSavingsProject.Supplier__c);
                  }
            }
        }

        if(!supplierIds.isEmpty()){
            SupplierService.updateSuppliers(supplierIds);            
        }

    }
}