objects/Procurement_Savings_Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Justification__c</fullName>
        <label>Justification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sites__c</fullName>
        <label>Site(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sites</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Procurement Savings Projects</relationshipLabel>
        <relationshipName>Procurement_Savings_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Procurement Savings Project</label>
    <nameField>
        <label>Procurement Savings Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procurement Savings Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Procurement_Savings_Project_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>April_Actual__c</fullName>
        <label>April Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>April_Forecast__c</fullName>
        <label>April Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>August_Actual__c</fullName>
        <label>August Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>August_Forecast__c</fullName>
        <label>August Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>December_Actual__c</fullName>
        <label>December Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>December_Forecast__c</fullName>
        <label>December Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>February_Actual__c</fullName>
        <label>February Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>February_Forecast__c</fullName>
        <label>February Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>January_Actual__c</fullName>
        <label>January Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>January_Forecast__c</fullName>
        <label>January Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>July_Actual__c</fullName>
        <label>July Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>July_Forecast__c</fullName>
        <label>July Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>June_Actual__c</fullName>
        <label>June Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>June_Forecast__c</fullName>
        <label>June Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>March_Actual__c</fullName>
        <label>March Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>March_Forecast__c</fullName>
        <label>March Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>May_Actual__c</fullName>
        <label>May Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>May_Forecast__c</fullName>
        <label>May Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>November_Actual__c</fullName>
        <label>November Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>November_Forecast__c</fullName>
        <label>November Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>October_Actual__c</fullName>
        <label>October Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>October_Forecast__c</fullName>
        <label>October Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Procurement_Savings_Project__c</fullName>
        <label>Procurement Savings Project</label>
        <referenceTo>Procurement_Savings_Project__c</referenceTo>
        <relationshipLabel>Procurement Savings Project Forecasts</relationshipLabel>
        <relationshipName>Procurement_Savings_Project_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>September_Actual__c</fullName>
        <label>September Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>September_Forecast__c</fullName>
        <label>September Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sites</valueSetName>
        </valueSet>
    </fields>
    <label>Procurement Savings Project Forecast</label>
    <nameField>
        <label>Procurement Savings Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procurement Savings Project Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Supplier__c.object
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Clinical</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Indirect Other</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Other</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Sites.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Berlin</fullName>
    </customValue>
    <customValue>
        <fullName>Bridgend</fullName>
    </customValue>
    <customValue>
        <fullName>Burlington</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Dublin</fullName>
    </customValue>
    <customValue>
        <fullName>Hay</fullName>
    </customValue>
    <customValue>
        <fullName>Melbourne</fullName>
    </customValue>
    <customValue>
        <fullName>Mississauga</fullName>
    </customValue>
    <customValue>
        <fullName>Ohio</fullName>
    </customValue>
    <customValue>
        <fullName>Philadelphia</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford</fullName>
    </customValue>
    <customValue>
        <fullName>San Diego</fullName>
    </customValue>
    <customValue>
        <fullName>Tredegar</fullName>
    </customValue>
    <masterLabel>Sites</masterLabel>
</GlobalValueSet>

classes/GenerateDataExt.cls
public Class GenerateDataExt{
    public Boolean dataGenerated{get;set;}
    public Boolean dataAlreadyGenerated{get;set;}
    
    public GenerateDataExt(){
        dataGenerated = false;
        
        List<Supplier__c> checkExistingSupplier = [select id from Supplier__c where Name = 'MintCRM'];
        
        if(checkExistingSupplier.size() > 0){
            dataAlreadyGenerated = true;
        }else{
            dataAlreadyGenerated = false;
        }
    }
    
    public void DeleteData(){
        delete [select id from Supplier__c];
        delete [select id from Procurement_Savings_Project__c];
        
        dataGenerated = false;
        dataAlreadyGenerated = false;
    }
    
    public void Generate(){
        Supplier__c sup = new Supplier__c();
        sup.Name = 'MintCRM';
        insert sup;
        
        List<Procurement_Savings_Project__c> projects = new List<Procurement_Savings_Project__c>();
        List<Procurement_Savings_Project_Forecast__c> forecasts = new List<Procurement_Savings_Project_Forecast__c>();
        
        Procurement_Savings_Project__c p1 = new Procurement_Savings_Project__c();
        p1.Supplier__c = sup.id;
        p1.Project_Start_Date__c = date.newInstance(date.today().year(),1,1);
        p1.Project_End_Date__c = date.newInstance(date.today().year(),12,31);
        p1.Sites__c = 'Bridgend';
        p1.Description__c = 'Project 1';
        p1.Division__c = 'Clinical';
        p1.Justification__c = 'For training purposes';
        p1.Name = 'Stationary';
        projects.add(p1);
        
        Procurement_Savings_Project__c p2 = new Procurement_Savings_Project__c();
        p2.Project_Start_Date__c = date.newInstance(date.today().year()+1,1,1);
        p2.Project_End_Date__c = date.newInstance(date.today().year()+1,12,31);
        p2.Sites__c = 'Dublin;Ohio';
        p2.Description__c = 'Project 2';
        p2.Division__c = 'Manufacturing';
        p2.Justification__c = 'For training purposes';
        p2.Name = 'Warehouse Equipment';
        projects.add(p2);
        
        Procurement_Savings_Project__c p3 = new Procurement_Savings_Project__c();
        p3.Project_Start_Date__c = date.newInstance(date.today().year(),1,1);
        p3.Project_End_Date__c = date.newInstance(date.today().year(),12,31);
        p3.Sites__c = 'Melbourne;Rockford;San Diego';
        p3.Description__c = 'Project 3';
        p3.Division__c = 'Corporate Other';
        p3.Justification__c = 'For training purposes';
        p3.Name = 'Customer Hosting Costs';
        projects.add(p3);
        
        insert projects;
        
        for(Procurement_Savings_Project__c p:projects){
            // split on sites - copy division
            
            List<String> sites = p.Sites__c.split(';');
            
            for(String s:sites){
                Procurement_Savings_Project_Forecast__c forecast = new Procurement_Savings_Project_Forecast__c();
                forecast.Procurement_Savings_Project__c = p.id;
                forecast.Name = p.Name + ' - ' + s;
                forecast.Site__c = s;
                forecast.Division__c = p.Division__c;
                
                forecast.January_Forecast__c = Integer.valueof((Math.random() * 10000));
                forecast.February_Forecast__c = Integer.valueof((Math.random() * 10000));
                forecast.March_Forecast__c = Integer.valueof((Math.random() * 10000));
                forecast.April_Forecast__c = Integer.valueof((Math.random() * 10000));
                forecast.May_Forecast__c = Integer.valueof((Math.random() * 10000));
                forecast.June_Forecast__c = Integer.valueof((Math.random() * 10000));
                forecast.July_Forecast__c = Integer.valueof((Math.random() * 10000));
                forecast.August_Forecast__c = Integer.valueof((Math.random() * 10000));
                forecast.September_Forecast__c = Integer.valueof((Math.random() * 10000));
                forecast.October_Forecast__c = Integer.valueof((Math.random() * 10000));
                forecast.November_Forecast__c = Integer.valueof((Math.random() * 10000));
                forecast.December_Forecast__c = Integer.valueof((Math.random() * 10000));
                
                forecast.January_Actual__c = Integer.valueof((Math.random() * 10000));
                forecast.February_Actual__c = Integer.valueof((Math.random() * 10000));
                forecast.March_Actual__c = Integer.valueof((Math.random() * 10000));
                forecast.April_Actual__c = Integer.valueof((Math.random() * 10000));
                forecast.May_Actual__c = Integer.valueof((Math.random() * 10000));
                forecast.June_Actual__c = Integer.valueof((Math.random() * 10000));
                forecast.July_Actual__c = Integer.valueof((Math.random() * 10000));
                forecast.August_Actual__c = Integer.valueof((Math.random() * 10000));
                forecast.September_Actual__c = Integer.valueof((Math.random() * 10000));
                forecast.October_Actual__c = Integer.valueof((Math.random() * 10000));
                forecast.November_Actual__c = Integer.valueof((Math.random() * 10000));
                forecast.December_Actual__c = Integer.valueof((Math.random() * 10000));
                
                forecasts.add(forecast);
            }
        }
        
        insert forecasts;
        
        dataGenerated = true;
    }
}