objects/Procurement_Savings_Project__c.object
<CustomObject>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Procurement Savings Projects</relationshipLabel>
        <relationshipName>Procurement_Savings_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Actuals__c</fullName>
        <label>Total Actuals</label>
        <summarizedField>Procurement_Savings_Project_Forecast__c.Total_Actuals__c</summarizedField>
        <summaryForeignKey>Procurement_Savings_Project_Forecast__c.Procurement_Savings_Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Forecast__c</fullName>
        <label>Total Forecast</label>
        <summarizedField>Procurement_Savings_Project_Forecast__c.Total_Forecast__c</summarizedField>
        <summaryForeignKey>Procurement_Savings_Project_Forecast__c.Procurement_Savings_Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Procurement Savings Project</label>
    <nameField>
        <label>Procurement Savings Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procurement Savings Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Supplier__c.object
<CustomObject>
    <fields>
        <fullName>No_of_Projects__c</fullName>
        <label>No. of Projects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Actual__c</fullName>
        <label>Total Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Forecast__c</fullName>
        <label>Total Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SupplierService.cls
public class SupplierService {
    public static void updateSuppliers(Set<Id> supplierIds){
        List<Supplier__c> suppliers = new List<Supplier__c>();
        List<AggregateResult> aggregateResults = [SELECT SUM(Total_Actuals__c)totalAct, SUM(Total_Forecast__c)totalFor,
                                                  COUNT(Id)ids, Supplier__c
                                                  FROM Procurement_Savings_Project__c 
                                                  WHERE Supplier__c IN : supplierIds GROUP BY Supplier__c];
        for(AggregateResult aggregateResult : aggregateResults){
            Supplier__c supplier = new Supplier__c();
            supplier.Total_Actual__c = (Decimal)aggregateResult.get('totalAct');
            supplier.Total_Forecast__c = (Decimal)aggregateResult.get('totalFor');
            supplier.No_of_Projects__c = (Integer)aggregateResult.get('ids');
            supplier.Id = (Id)aggregateResult.get('Supplier__c');
            suppliers.add(supplier);
        }

        if(!suppliers.isEmpty()){
            update suppliers;
        }
    }
}